### ISSUE TITLE
Busted pip installation

### ISSUE THREAD

**Issue by martinthomson** [MikeBishop/archive-repo#12]
This is from the i-d-template actions image.

```
bash-5.1# python3 -m archive-repo
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/archive-repo/__main__.py", line 1, in <module>
    from . import archive, pr_branches
  File "/usr/lib/python3.8/site-packages/archive-repo/archive.py", line 14, in <module>
    from .shared import archive_reference
ModuleNotFoundError: No module named 'archive-repo.shared'
```

**Comment by MikeBishop** [comment]
It appears that because the `shared` folder didn't have an `__init__.py` file, it wasn't being included in the package.  I've verified that the shared folder is now being populated in a fresh virtualenv.
